### ISSUE TITLE
Avaliar um caso real de aplicação dos princípios FAIR para dados abertos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/open-metadata#1]
Os princípios FAIR - https://www.go-fair.org/fair-principles/

Caso realmente de aplicação, com a respectiva explicação daquilo que foi feito para cumprir com cada critério - https://about.zenodo.org/principles/

**Comment by viniciusandrade** [comment]
Uma primeira adaptação da página de aplicação dos princípios FAIR esta disponível para melhorias em:

https://openmetadata.teste.bvsalud.org/principios-fair/

**Comment by renatomurasaki** [comment]
Revisão realizada no texto da página, incluindo uma auto-avaliação da aderência a cada princípio, considerando o que o site FAIR preconiza para cada um deles.
