### ISSUE TITLE
Realizar tradução das páginas do site para o espanhol

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/open-metadata#10]
Criar documento no SharingPoint com os textos traduzidos e quando finalizado informar por aqui marcando o @marcioalvessilva para atualização do site em produção.

Obs. A tradução das tabelas do dicionário de dados (página Detalhes do formato) e campos de pesquisa (página Informações detalhadas) estão sendo realizadas em uma planilha no SharingPoint e serão atualizas depois.

**Comment by marcoslmori** [comment]
https://paho.sharepoint.com/:w:/r/sites/BIR/TC/TC/Gerencias/MTI/DES/metadados-abertos/trad-site-es.docx?d=w6a323a1c29504f5f9e9230002ec7cbbc&csf=1&web=1&e=mD0eHO

**Comment by marcoslmori** [comment]
vinicius "As tabelas das páginas "Detalhes do formato"  e "Informações avançadas" eu já fiz a tradução e vou atualizar quando os textos estiverem ok"

**Comment by marcoslmori** [comment]
Páginas traduzidas

- Home
- Como usar
- Interface de busca
- Detalhes do formato
- Informações avançadas
- Princípios FAIR

**Comment by marcioalvessilva** [comment]
Versão espanhol cadastrada!
Aguardando tabelas para finalizar a versão espanhol

Páginas com tabelas 
- https://openmetadata.bvsalud.org/language/es/detalles-de-formato/
- https://openmetadata.bvsalud.org/language/es/informacion-avanzada/

**Comment by viniciusandrade** [comment]
@marcioalvessilva colei as tabelas nas páginas indicadas.  

Você consegue ajustar o plugin de idiomas para suprimir o /language/ nas urls para ficar no mesmo padrão dos demais sites?

Obrigado.

**Comment by marcioalvessilva** [comment]
@viniciusandrade já ajustei no plugin, preciso agora conferir os links

**Comment by marcioalvessilva** [comment]
@marcoslmori @viniciusandrade, @heitorbarbieri - link ajustados, por favor validar a tradução para espanhol.

**Comment by viniciusandrade** [comment]
Conteúdo atualizado no site pelo @marcioalvessilva.
