### ISSUE TITLE
Replicar estrutura do site  para os idiomas inglês e espanhol

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/open-metadata#11]
- Preservar os elementos existentes na versão finalizada em português 
- Manter a caixa de formatos disponíveis (XML, JSON, RIS, CSV e RSS) pois este dado não precisa de tradução
- Atualizar imagens da página Interface de busca para os idiomas inglês e espanhol.

**Comment by viniciusandrade** [comment]
@marcioalvessilva por favor quando possível criar estrutura do site em espanhol e colar os textos traduzidos pelo @marcoslmori informados em https://github.com/bireme/open-metadata/issues/10

**Comment by marcioalvessilva** [comment]
Grato! Assim que possível inicio as traduções!

**Comment by marcioalvessilva** [comment]
Traduções concluídas!
