### ISSUE TITLE
Tradução para espanhol e inglês das tabelas de campos de busca e dicionário de dados

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/open-metadata#12]
Realizar a tradução nas planilhas do Sharingpoint para posterior atualização no site nos idiomas correspondentes.

**Comment by marcoslmori** [comment]
es: https://paho.sharepoint.com/:w:/r/sites/BIR/TC/TC/Gerencias/MTI/DES/metadados-abertos/trad-site-es.docx?d=w6a323a1c29504f5f9e9230002ec7cbbc&csf=1&web=1&e=YNKqQi

wn: https://paho.sharepoint.com/:w:/r/sites/BIR/TC/TC/Gerencias/MTI/DES/metadados-abertos/trad-site-en.docx?d=w2ec1120f749b45bdbaf46d35b08ea5af&csf=1&web=1&e=wetTqB

**Comment by viniciusandrade** [comment]
Traduções realizadas nas planilhas "iahx-dicionario-de-dados" e "iahx-campos-de-busca" aguardando finalização do issues #9 e #10 para publicação no site.

**Comment by viniciusandrade** [comment]
Tabelas incoporadas no site pelo @marcioalvessilva com ajuste do caracter ```"``` trocado pela entidade ```&#34;```
