### ISSUE TITLE
Desenvolver nome para o header em outros idiomas

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/open-metadata#4]
@renatomurasaki - Por favor criar os headers em En, Es e Fr para o portal de Metadados Abertos
Ex: Metadados Abertos das Bases Bibliográficas da BVS BETA - PT.
Grato!

**Comment by renatomurasaki** [comment]
PT - Metadados Abetros das Fontes de Informação da BVS BETA
ES - Metadatos Abiertos de las Fuentes de Información de la BVS BETA
EN - Open Metadata of the VHL Information Sources
FR - Métadonnées ouvertes des sources d'information VHL

@viniciusandrade @heitorbarbieri @marcoslmori concordam com a mudança do header? Ao invés de bases bibliográficas da BVS, estou sugerindo Fontes de Informação da BVS.

**Comment by viniciusandrade** [comment]
:+1:

**Comment by marcioalvessilva** [comment]
@renatomurasaki , fiquei com uma dúvida - a palavra "beta" não vai aparecer em EN e FR?

Exemplos:

![image](https://user-images.githubusercontent.com/48724136/124491461-b4e38600-dd89-11eb-8bed-f8fde76ab025.png)

**Comment by renatomurasaki** [comment]
@marcioalvessilva sim, vai, mas não traduz, continua beta
