### ISSUE TITLE
Atualizar HTML da tabela de Campos de Pesquisa

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/open-metadata#7]
@viniciusandrade atualizar, por favor, a tabela disponível em https://openmetadata.teste.bvsalud.org/informacoes-avancadas/

MS Excel **iahx-campos-de-busca.xlsx** disponível no sharepoint atualizado no idioma português

**Comment by viniciusandrade** [comment]
Página atualizada.

**Comment by renatomurasaki** [comment]
Obrigado
