### ISSUE TITLE
Verificar as páginas no site em produção que mostram os formatos de exportação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/open-metadata#8]
As páginas

https://openmetadata.bvsalud.org/como-usar/
https://openmetadata.bvsalud.org/detalhes-do-formato/

Estão mostrando todo o formato de exportação sem limitar o tamanho da caixa para fazer scroll.

No teste está assim:

![image](https://user-images.githubusercontent.com/1226218/131907354-e25cfae0-4ead-40cb-85b9-528dfb35a752.png)

Na produção está sem o scroll:

![image](https://user-images.githubusercontent.com/1226218/131907463-7aec4217-dfd4-4c65-b030-a641147f256a.png)

**Comment by marcoslmori** [comment]
Já foi solicitado para o Marco atualizar o tema na produção

**Comment by marcoslmori** [comment]
Atualizado o tema em produção, o scrool voltou por favor, validar

**Comment by renatomurasaki** [comment]
Resolvido. Obrigado
