### ISSUE TITLE
Realizar tradução das páginas do site para o inglês

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/open-metadata#9]
Criar documento no SharingPoint com os textos traduzidos e quando finalizado informar por aqui marcando o @marcioalvessilva para atualização do site em produção.

Obs. A tradução das tabelas do dicionário de dados (página Detalhes do formato) e campos de pesquisa (página Informações detalhadas) estão sendo realizadas em uma planilha no SharingPoint e serão atualizas depois.

**Comment by marcoslmori** [comment]
documento no sharepoint https://paho.sharepoint.com/:w:/r/sites/BIR/TC/TC/Gerencias/MTI/DES/metadados-abertos/trad-site-es.docx?d=w6a323a1c29504f5f9e9230002ec7cbbc&csf=1&web=1&e=hf5Oo0

**Comment by heitorbarbieri** [comment]
Por favor, @marcioalvessilva , verifique se o documento atende às expectativas. Obrigado.

**Comment by marcioalvessilva** [comment]
Grato Heitor, páginas em inglês traduzidas, pendente apenas as tabelas

Segue link de páginas com tabelas 
- https://openmetadata.bvsalud.org/en/format-details/
- https://openmetadata.bvsalud.org/en/advanced-information/

@viniciusandrade , @marcoslmori e @heitorbarbieri, por favor, validar!

**Comment by heitorbarbieri** [comment]
@viniciusandrade, por favor, confirme quem deve traduzir as tabelas em inglês.

**Comment by viniciusandrade** [comment]
@heitorbarbieri pode ficar tranquilo pois as tabelas já estão traduzidas no Sharingpoint e o Marcio esta dando uma força para converter as tabelas para HTML e colar no site.

**Comment by heitorbarbieri** [comment]
Obrigado.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by viniciusandrade** [comment]
Conteúdo atualizado no site pelo @marcioalvessilva.
